### POST EVENT 
POST http://localhost:3000/api/memory_management/event
Content-Type: application/json

{
    "_idWork": "WUPE-R8BIwI7CAR",
    "_name": "testingEventUsernamexxx",
    "_kind": "testingEventTypexxx"
}

### GET EVENTS
GET http://localhost:3000/api/memory_management/event

### GET EVENT
GET http://localhost:3000/api/memory_management/event/lD48wkcac5iFbGH

### UPDATE EVENT
PUT http://localhost:3000/api/memory_management/event/lD48wkcac5iFbGH
Content-Type: application/json

{
    "_idWork": "WUPE-R8BIwI7CAR",
    "_name": "updated name",
    "_kind": "updated kind"
}
### DELETE EVENTS
DELETE http://localhost:3000/api/memory_management/event

### DELETE EVENT
DELETE http://localhost:3000/api/memory_management/event/lD48wkcac5iFbGH