### POST  MEMORY
POST http://localhost:3000/api/memory_management/memory
Content-Type: application/json

{
    "_idUser": "JCVc8",
    "_name": "memory 1",
    "_description": "first memory"
}

### GET MEMORIES
GET http://localhost:3000/api/memory_management/memory

### GET MEMORY
GET http://localhost:3000/api/memory_management/memory/99FT_pokaC

### UPDATE MEMORY
PUT http://localhost:3000/api/memory_management/memory/99FT_pokaC
Content-Type: application/json

{
    "_idUser": "JCVc8",
    "_name": "memory 1 updated",
    "_description": "first memory updated"
}
### DELETE MEMORIES
DELETE http://localhost:3000/api/memory_management/memory

### DELETE MEMORY
DELETE http://localhost:3000/api/memory_management/memory/CtQzvqgrhz