### POST PARTITION 
POST http://localhost:3000/api/memory_management/partition
Content-Type: application/json

{
    "_idMemory" : "99FT_pokaC",
    "_position"  : 1,
    "_size"   : 1,
    "_busy"   : 1,
    "_state"    : "estate"
}

### GET PARTITIONS
GET http://localhost:3000/api/memory_management/partition

### GET PARTITION
GET http://localhost:3000/api/memory_management/partition/RH42CUslKAithOu

### UPDATE PARTITION
PUT http://localhost:3000/api/memory_management/partition/RH42CUslKAithOu
Content-Type: application/json

{
    "_idMemory" : "99FT_pokaC",
    "_position"  : 2,
    "_size"   : 2,
    "_busy"   : 2,
    "_state"    : "updatedEstate"
}
### DELETE PARTITIONS
DELETE http://PARTITIONShost:3000/api/memory_management/partition

### DELETE PARTITION
DELETE http://localhost:3000/api/memory_management/partition/T69tDMA4c0oQ93Z