### POST WORK 
POST http://localhost:3000/api/memory_management/work
Content-Type: application/json

{
    "_idPartition": "RH42CUslKAithOu",
    "_name": "testingNameWork",
    "_weight": 1,
    "_state": 0
}

### GET WORKS
GET http://localhost:3000/api/memory_management/work

### GET WORK
GET http://localhost:3000/api/memory_management/work/5luVOlq63pZiRYa

### UPDATE WORK
PUT http://localhost:3000/api/memory_management/work/5luVOlq63pZiRYa
Content-Type: application/json

{
    "_idPartition": "RH42CUslKAithOu",
    "_name": "updated partition",
    "_weight": 2,
    "_state": 1
}

### DELETE WORKS
DELETE http://localhost:3000/api/memory_management/work


### DELETE WORK
DELETE http://localhost:3000/api/memory_management/work/5luVOlq63pZiRYa