### POST USER 
POST http://localhost:3000/api/user/user
Content-Type: application/json

{
    "_name": "lord Horus",
    "_password": "lordhorus123",
    "_username": "lordHorus",
    "_mail": "lordHorus@gmail.com"
}

### GET USERS
GET http://localhost:3000/api/user/user

### GET USER
GET http://localhost:3000/api/user/user/uykME

### UPDATE USER
PUT http://localhost:3000/api/user/user/uykME
Content-Type: application/json

{
    "_name": "lord Horus updated",
    "_password": "lordhorus123 updated",
    "_username": "lordHorus updated",
    "_mail": "lordHorusupdated@gmail.com"
}
### DELETE USERS
DELETE http://localhost:3000/api/user/user

### DELETE USER
DELETE http://localhost:3000/api/user/user/uykME

### id to test = uykME (got of nanoid(5))